### ISSUE TITLE
Build Shopping Screen and Functionality

### ISSUE THREAD

**Issue by Jubibani** [Jubibani/cc17-3f-the-boys#1]
**Objective:** Implement the user interface for the shopping screen.
**Requirements:**
- Display product listings with images, names, prices.
- Allow filtering by categories or price.
- Include "Add to Cart" button for each product.
- can edit the included products inside the cart.

**Acceptance Criteria:**
- Users can view all products and filter by categories or price.
- Users can add and delete products to the cart.

**Comment by CHARLESAGANO** [comment]
Finish doing my task in figma

**Comment by Jubibani** [comment]
Hello, How is the work going?

**Comment by CHARLESAGANO** [comment]
Just started learning and implementing View Groups and drawables
