### ISSUE TITLE
Build Cart Screen and Functionality

### ISSUE THREAD

**Issue by Jubibani** [Jubibani/cc17-3f-the-boys#2]
**Objective:** Create the cart screen where users can view selected items.
**Requirements:**

- Show a list of items in the cart with prices and quantities.
- Provide the ability to update item quantities or remove items.
- Display total cost and checkout button.

**Acceptance Criteria:**

- Users can view, update, or remove items from the cart.

**Comment by CHARLESAGANO** [comment]
Finished doing my task in figma
