### ISSUE TITLE
Build user  User Profile Screen and Functionality

### ISSUE THREAD

**Issue by Jubibani** [Jubibani/cc17-3f-the-boys#5]
**Objective:** Create a screen where users can view and edit their profile information.
**Requirements:**

- Show user's name, profile picture, bio, and activity (posts, likes).
- Include an option to edit profile details.
- Provide a follow/unfollow button for other users' profiles.
- can be deleted
- functional

**Acceptance Criteria:**

- Users can view and update their profile.
- Users can view other profiles and follow/unfollow them.

**Comment by ChrisPaoloSab-it** [comment]
created a profile page for the user, adding more interactive elements to create a more high-fidelity like setup

**Comment by ChrisPaoloSab-it** [comment]
improving user profile screen to reflect essential features and primary information required for the app
